before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: O35InO60Edl/iSuJxGRzIe/plz3Pm5rJoFUBYEOZGJ7Db1ZpDlsF6GC2MsYYMEk0Y7QM2ZwEidKydjHCkO/FGzyZo6kBwCVOhRXNMNoruQxCXF6oCNzjidHfxg4IY1G8ggUMUmchaby2hYjoJyFQy7ZQJnW6RViWMrDbEnE4R8RJTC8uM8IHUZBUwizlSeCdW6NcNx68/wr10vMN3sd2XhcIhZzALS06mP7ukPHirX0SgIQg10knrsA4qk2nn3p/uDd0dPjz92syjIaCspVWoZ/Ul9q+LB3EeIFIWSFV1LghEm1rPU9O4m5SXNPex0tqH+QkXhV3wX4XuyR/LLlbltbJAPuUChz2y61IQ3vlnQvWlITjN2bTjZBuO3CbNZTFr5EQkABgX6c1LTycUTpumy/QdkclCyqLU9bqA4jlyCJPI9y/Z0xc22iHvpuBd7PxCD+VKLImpFk8eQTh1hjKrsQMyELAxfGWY9OxGbJdyva8voHyLruBWiUTjoQ/tmEDzRAYdJ+pq7yR6K7W+mYn6fLvo1kyWKHLqeupXr2/F9NTF7/7l0vrfqZsyay7ZeA5Fug189eLbHHYpm+ujooPFmN33rQ5rDYKGC/4g2I+ZxgDv8EME9ETYBXP2wg643+EhI+CAWRDsI5NtiboqUic60R839hor7VosgIiTDHRpj0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
